name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app -r requirements.txt

    - name: Create setup.py
      run: |
        echo "from setuptools import setup" > setup.py
        echo "APP = ['Controller suggest.py']" >> setup.py
        echo "OPTIONS = {'argv_emulation': True}" >> setup.py
        echo "setup(app=APP, options={'py2app': OPTIONS})" >> setup.py

    - name: Build macOS app
      run: |
        python setup.py py2app

    - name: Upload app bundle
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-macOS
        path: dist/*.app
